parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            bool $isDebug: '%kernel.debug%'
            string $appEmail: '%env(APP_EMAIL)%'
            string $appDomain: '%env(APP_DOMAIN)%'

    _instanceof:
        Common\Application\Bus\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        Common\Application\Bus\EventHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

    Auth\:
        resource: '../src/Auth'
        exclude:
            - '../src/Auth/{Kernel.php,*Dto.php}'
            - '../src/Auth/{Entity,Enum,Event}'

    Common\:
        resource: '../src/Common'
        exclude:
            - '../src/Common/{Kernel.php,*Dto.php}'
            - '../src/Common/{Entity,Enum,Event}'

    UI\:
        resource: '../src/UI'
        exclude:
            - '../src/UI/**/{*Command.php,*Query.php,*Response.php,*Request.php}'

    # Subscriber and Listeners
    UI\Http\Common\Listener\ExceptionListener:
        tags: [ { name: 'kernel.event_listener', event: kernel.exception, priority: 10 } ]

    UI\Http\Common\Listener\ResponseListener:
        tags: [ { name: 'kernel.event_listener' } ]


    # Another services
    UI\Http\Common\Exception\Resolver:
        arguments: [ '%exceptions%' ]

    UI\Http\Common\Request\RequestArgumentResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 150 }