parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Infra\:
        resource: '../src/Infra'
        exclude:
            - '../src/Infra/{Kernel.php}'
            - '../src/Infra/{Entity,Enum,Event}'
