parameters:
    app.email: 'bunches.app@mail.ru'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            bool $isDebug: '%kernel.debug%'
            string $appEmail: '%app.email%'

    _instanceof:
        Common\Application\Bus\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        Common\Application\Bus\EventListenerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

    Auth\:
        resource: '../src/Auth'
        exclude:
            - '../src/Auth/{Kernel.php,*Dto.php}'
            - '../src/Auth/{Entity,Enum,Event}'

    Common\:
        resource: '../src/Common'
        exclude:
            - '../src/Common/{Kernel.php,*Dto.php}'
            - '../src/Common/{Entity,Enum,Event}'

    UI\:
        resource: '../src/UI'
        exclude:
            - '../src/UI/**/{*Command.php,*Query.php,*Response.php,*Request.php}'

    # Subscriber and Listeners
    UI\Http\Common\Subscriber\ExceptionListener:
        tags: [ { name: 'kernel.event_listener', event: kernel.exception, priority: 10 } ]

    UI\Http\Common\Subscriber\ResponseListener:
        tags: [ { name: 'kernel.event_listener' } ]

    Common\Application\Subscriber\DomainEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    # Another services
    UI\Http\Common\Exception\Resolver:
        arguments: [ '%exceptions%' ]

    UI\Http\Common\Request\RequestArgumentResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 150 }

    Common\Infra\FixPostgreSQLDefaultSchemaListener:
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema }