services:
    _defaults:
        autowire: true
        autoconfigure: true

    oneup_flysystem.s3_filesystem_filesystem:
        class: League\Flysystem\Filesystem
        public: true
        arguments:
            $adapter: '@oneup_flysystem.s3_adapter_adapter'

    CoreKit\Infra\FileStorage\S3StorageClient:
        arguments:
            $s3FileSystem: '@oneup_flysystem.s3_filesystem_filesystem'
        public: true

    Test\:
        resource: '%kernel.project_dir%/tests/Test/**/*Fixture.php'
