# bb - backend "bundle", bundle - имя проекта
services:
    traefik:
        container_name: bb-traefik
        image: traefik:v2.10.4
        command:
            --providers.docker=true
            --providers.docker.exposedByDefault=false
            --entryPoints.http.address=:80
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-network
        networks:
            - traefik-network

    postgres:
        container_name: bb-postgres
        image: postgres:15.4-alpine
        volumes:
            - vol-postgres:/var/lib/postgresql/data
            - ./backend/docker/development/create-test-database.sh:/docker-entrypoint-initdb.d/create-test-database.sh
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
            POSTGRES_DB: app
            POSTGRES_TEST_DB: test
        ports:
            - "54321:5432"
        secrets:
            - db_password

    php-fpm:
        container_name: bb-php-fpm
        build:
            context: ./backend/docker/development/fpm
        environment:
            PHP_IDE_CONFIG: "serverName=bb.local"
            S3_ACCESS_KEY_ID: /run/secrets/s3_access_key
            S3_SECRET_KEY: /run/secrets/s3_secret_key
            S3_BUCKET: "blog-dev"
            S3_ENDPOINT: "http://minio:9000"
        volumes:
            - ./backend/:/app
        depends_on:
            - postgres
        secrets:
            - s3_access_key
            - s3_secret_key

    php-cli:
        container_name: bb-php-cli
        build:
            context: ./backend/docker/development/cli
        environment:
            PHP_IDE_CONFIG: "serverName=bb.local"
        volumes:
            - ./:/app
            - vol-composer:/root/.composer/cache
        depends_on:
            - postgres

    nginx:
        container_name: bb-nginx
        build:
            context: ./backend/docker/development/nginx
        volumes:
            - ./backend/:/app
        depends_on:
            - php-fpm
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-network
            - traefik.http.routers.bb-nginx.rule=Host(`bb.localhost`)
            - traefik.http.routers.bb-nginx.entryPoints=http
            - traefik.http.services.bb-nginx.loadBalancer.server.port=80
        networks:
            - traefik-network
            - default

    admin-nginx:
        container_name: fb-admin-nginx
        build:
            context: frontend/admin/docker/development/nginx
        depends_on:
            - traefik
        networks:
            - traefik-network
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-network
            - traefik.http.routers.fb-admin-nginx.rule=Host(`admin.localhost`)
            - traefik.http.routers.fb-admin-nginx.entryPoints=http
            - traefik.http.services.fb-admin-nginx.loadBalancer.server.port=80
            - traefik.http.middlewares.admin-redirect.redirectRegex.regex=^(https?://)admin.localhost/(.*)
            - traefik.http.middlewares.admin-redirect.redirectRegex.replacement=$${1}admin.localhost/$${2}
            - traefik.http.middlewares.admin-redirect.redirectRegex.permanent=true
            - traefik.http.routers.fb-admin-nginx.middlewares=admin-redirect

    node:
        container_name: fb-admin-node
        build:
            context: frontend/admin/docker/development/node
        depends_on:
            - admin-nginx
        volumes:
            - ./frontend/admin:/app
        tty: true

    mailer:
        container_name: bb-mailer
        image: mailhog/mailhog
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-network
            - traefik.http.routers.bb-mailer.rule=Host(`mailer.localhost`)
            - traefik.http.routers.bb-mailer.entryPoints=http
            - traefik.http.services.bb-mailer.loadBalancer.server.port=8025
        networks:
            - traefik-network
            - default

    minio:
        container_name: bb-minio
        image: 'bitnami/minio:2024.7.31'
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-network
            - traefik.http.routers.bb-minio.rule=Host(`minio.localhost`)
            - traefik.http.routers.bb-minio.entryPoints=http
            - traefik.http.services.bb-minio.loadBalancer.server.port=9011
        environment:
            MINIO_ROOT_USER: minio-root-user
            MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_password
            MINIO_CONSOLE_PORT_NUMBER: 9011
        networks:
            - traefik-network
            - default
        volumes:
            - vol-minio:/bitnami/minio/data
        secrets:
            - minio_root_password

#    zookeeper:
#        image: bitnami/zookeeper:latest
#        container_name: bb-zookeeper
#        ports:
#            - "2181:2181"
#        environment:
#            - ALLOW_ANONYMOUS_LOGIN=yes
#        volumes:
#            - vol-zookeeper:/bitnami/zookeeper
#
#    kafka:
#        image: 'bitnami/kafka:latest'
#        container_name: bb-kafka
#        ports:
#            - '9092:9092'
#        environment:
#            - KAFKA_BROKER_ID=1
#            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#            - ALLOW_PLAINTEXT_LISTENER=yes
#        volumes:
#            - vol-kafka:/bitnami/kafka
#        depends_on:
#            - zookeeper
#
#    kafka-ui:
#        image: provectuslabs/kafka-ui:v0.6.2
#        container_name: bb-kafka-ui
#        ports:
#            - "8080:8080"
#        restart: always
#        environment:
#            - KAFKA_CLUSTERS_0_NAME=local
#            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
#            - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
#            - KAFKA_CLUSTERS_0_READONLY=false
#            - DYNAMIC_CONFIG_ENABLED=true
#        depends_on:
#            - zookeeper
#            - kafka
#        labels:
#            - traefik.enable=true
#            - traefik.docker.network=traefik-shop
#            - traefik.http.routers.bb-kafka-ui.rule=Host(`kafka-shop.localhost`)
#            - traefik.http.routers.bb-kafka-ui.entryPoints=http
#            - traefik.http.services.bb-kafka-ui.loadBalancer.server.port=8080

secrets:
    db_password:
        file: ./extra/docker/development/secrets/db_password
    minio_root_password:
        file: ./extra/docker/development/secrets/minio_root_password
    s3_access_key:
        file: ./extra/docker/development/secrets/s3_access_key
    s3_secret_key:
        file: ./extra/docker/development/secrets/s3_secret_key

volumes:
    vol-postgres:
    vol-composer:
    vol-minio:
#    vol-zookeeper:
#    vol-kafka:

networks:
    traefik-network:
        name: pro-bundle_traefik-network
