# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        cache_adapter:
            local:
                location: '%kernel.cache_dir%'

        s3_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(S3_BUCKET)%'
                prefix: ''

    filesystems:
        cache:
            adapter: cache_adapter
            alias: cache_storage
        s3_filesystem:
            adapter: s3_adapter
            alias: s3_filesystem

services:
    Aws\S3\S3Client:
        arguments:
            - version: 'latest'
            - region: 'default'
            - endpoint: '%env(S3_ENDPOINT)%'
            - use_path_style_endpoint: true
            - credentials:
                key: '%env(S3_ACCESS_KEY_ID)%'
                secret: '%env(S3_SECRET_KEY)%'
            - retries:
                mode: 'standard'
                max_attempts: 5
