security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        auth_module_provider:
            id: Auth\Infra\User\Service\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/api
            lazy: true
#            provider: users_in_memory

    access_control:
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/v1/service/ping, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/v1/sign-up, roles: PUBLIC_ACCESS }

when@test:
    security:
        firewalls:
            dev:
                pattern: ^/
                security: false

        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
