security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        auth_module_provider:
            id: Auth\Infra\User\Service\Security\UserProvider

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            user_checker: Auth\Infra\User\Service\Security\UserChecker
            jwt: ~
            refresh_jwt:
                check_path: api_refresh_token
                provider: auth_module_provider
            entry_point: jwt

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/api/(login|token/refresh), roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/v1/service/ping, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/v1/sign-up, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/v1/confirm-email, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        firewalls:
            dev:
                pattern: ^/
                security: false

        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
